
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - task-network
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - sqlserver
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "5000:5000"
    networks:
      - task-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:5000
    ports:
      - "${FRONTEND_PORT}:4200"
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  sqlserver_data:
